server.port=${PORT:8080}
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Firebase configuration
firebase.project.id=${FIREBASE_PROJECT_ID:seemee-user-service}
