spring.application.name=userservice
server.port=${PORT:8080}
# Allow external access to the application
server.address=0.0.0.0

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://krishk:uh3RIF6cWPWLvFiA@cluster0.szsml.mongodb.net/SeeMee?retryWrites=true&w=majority
spring.data.mongodb.database=SeeMee


# Actuator for health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.com.seemee.userservice=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.data.mongodb=DEBUG

# Dev mode configurations
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

# Application URLs
app.frontend.url=https://seemee-759f4.web.app/
app.email.from=${EMAIL_FROM:noreply@seemee.com}


spring.mail.username=sivakreddy.k7@gmail.com
spring.mail.password=eerjbdyoxsltzmqc